-- Normalize non Tax Engine / non Statutory Setup JSON into tables.
-- Keep PayrollSetups.SetupJson only as compatibility storage for tax/statutory blocks.

USE payroll;

CREATE TABLE IF NOT EXISTS SalaryComponents (
    Id BIGINT PRIMARY KEY,
    Code VARCHAR(80) NOT NULL,
    ComponentType VARCHAR(120) NOT NULL DEFAULT '',
    Category VARCHAR(60) NOT NULL DEFAULT 'Earning',
    Name VARCHAR(160) NOT NULL,
    PayType VARCHAR(60) NOT NULL DEFAULT 'Fixed Pay',
    CalculationType VARCHAR(80) NOT NULL DEFAULT 'Fixed Amount',
    ValueText VARCHAR(500) NOT NULL DEFAULT '',
    Formula VARCHAR(1000) NOT NULL DEFAULT '',
    BaseComponent VARCHAR(80) NOT NULL DEFAULT '',
    Taxable BOOLEAN NOT NULL DEFAULT TRUE,
    Ctc BOOLEAN NOT NULL DEFAULT TRUE,
    ProRata BOOLEAN NOT NULL DEFAULT TRUE,
    Fbp BOOLEAN NOT NULL DEFAULT FALSE,
    RestrictFbp BOOLEAN NOT NULL DEFAULT FALSE,
    Epf VARCHAR(40) NOT NULL DEFAULT 'Never',
    Esi BOOLEAN NOT NULL DEFAULT FALSE,
    Recurring BOOLEAN NOT NULL DEFAULT TRUE,
    Scheduled BOOLEAN NOT NULL DEFAULT FALSE,
    InvestmentType VARCHAR(120) NOT NULL DEFAULT '',
    CorrectionOf VARCHAR(120) NOT NULL DEFAULT '',
    Active BOOLEAN NOT NULL DEFAULT TRUE,
    Priority INT NOT NULL DEFAULT 999,
    UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UX_SalaryComponents_Code (Code)
);

CREATE TABLE IF NOT EXISTS SalaryStructures (
    Id BIGINT PRIMARY KEY,
    ClientId INT NOT NULL DEFAULT 0,
    ClientRef VARCHAR(200) NOT NULL DEFAULT '',
    Name VARCHAR(200) NOT NULL DEFAULT '',
    AnnualCtc DECIMAL(18,2) NOT NULL DEFAULT 0,
    Active BOOLEAN NOT NULL DEFAULT TRUE,
    UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS SalaryStructureLines (
    Id BIGINT PRIMARY KEY AUTO_INCREMENT,
    StructureId BIGINT NOT NULL,
    ComponentId VARCHAR(80) NOT NULL,
    ValueText VARCHAR(1000) NOT NULL DEFAULT '',
    SortOrder INT NOT NULL DEFAULT 0,
    UNIQUE KEY UX_SalaryStructureLines_Structure_Component (StructureId, ComponentId)
);

CREATE TABLE IF NOT EXISTS PayslipTemplates (
    Id BIGINT PRIMARY KEY,
    ClientId INT NOT NULL DEFAULT 0,
    ClientRef VARCHAR(200) NOT NULL DEFAULT '',
    Name VARCHAR(200) NOT NULL DEFAULT '',
    Theme VARCHAR(80) NOT NULL DEFAULT 'Classic',
    ShowLogo BOOLEAN NOT NULL DEFAULT TRUE,
    ShowClient BOOLEAN NOT NULL DEFAULT TRUE,
    ShowYtd BOOLEAN NOT NULL DEFAULT TRUE,
    ShowBank BOOLEAN NOT NULL DEFAULT TRUE,
    Note VARCHAR(1000) NOT NULL DEFAULT '',
    Active BOOLEAN NOT NULL DEFAULT TRUE,
    UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PayrollSchedules (
    Id INT PRIMARY KEY DEFAULT 1,
    WorkWeek VARCHAR(80) NOT NULL DEFAULT 'Monday - Friday',
    SalaryDays VARCHAR(80) NOT NULL DEFAULT 'Actual days',
    FixedDays VARCHAR(10) NOT NULL DEFAULT '30',
    PayDay VARCHAR(80) NOT NULL DEFAULT 'Last working day',
    FirstPayPeriod VARCHAR(7) NOT NULL DEFAULT '',
    UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ClientPaySchedules (
    ClientId INT PRIMARY KEY,
    WorkWeek VARCHAR(80) NOT NULL DEFAULT 'Monday - Friday',
    SalaryDays VARCHAR(80) NOT NULL DEFAULT 'Actual days',
    FixedDays VARCHAR(10) NOT NULL DEFAULT '30',
    PayDay VARCHAR(80) NOT NULL DEFAULT 'Last working day',
    FirstPayPeriod VARCHAR(7) NOT NULL DEFAULT '',
    UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS EmployeeSalaryComponents (
    Id BIGINT PRIMARY KEY AUTO_INCREMENT,
    EmployeeId INT NOT NULL,
    ComponentId VARCHAR(80) NOT NULL,
    ComponentCode VARCHAR(80) NOT NULL DEFAULT '',
    Amount DECIMAL(18,4) NOT NULL DEFAULT 0,
    UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UX_EmployeeSalaryComponents_Employee_Component (EmployeeId, ComponentId)
);

CREATE TABLE IF NOT EXISTS EmployeePersonalDetails (
    EmployeeId INT PRIMARY KEY,
    DateOfBirth VARCHAR(30) NOT NULL DEFAULT '',
    Mobile VARCHAR(50) NOT NULL DEFAULT '',
    PanNumber VARCHAR(50) NOT NULL DEFAULT '',
    AadhaarNumber VARCHAR(50) NOT NULL DEFAULT '',
    UanNumber VARCHAR(50) NOT NULL DEFAULT '',
    EsicNumber VARCHAR(50) NOT NULL DEFAULT '',
    Source VARCHAR(120) NOT NULL DEFAULT '',
    SourceLocation VARCHAR(200) NOT NULL DEFAULT '',
    City VARCHAR(100) NOT NULL DEFAULT '',
    District VARCHAR(100) NOT NULL DEFAULT '',
    State VARCHAR(100) NOT NULL DEFAULT '',
    RawDesignation VARCHAR(160) NOT NULL DEFAULT '',
    OriginalEmployeeCode VARCHAR(80) NOT NULL DEFAULT '',
    DuplicateResolution VARCHAR(500) NOT NULL DEFAULT '',
    ExcelRow INT NOT NULL DEFAULT 0,
    EsicEmployee DECIMAL(18,4) NOT NULL DEFAULT 0,
    PtLwfWorkmenComp DECIMAL(18,4) NOT NULL DEFAULT 0,
    Tds DECIMAL(18,4) NOT NULL DEFAULT 0,
    Recovery DECIMAL(18,4) NOT NULL DEFAULT 0,
    UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS EmployeePaymentDetails (
    EmployeeId INT PRIMARY KEY,
    BankAccountNo VARCHAR(100) NOT NULL DEFAULT '',
    IfscCode VARCHAR(40) NOT NULL DEFAULT '',
    UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PayRunEmployeeLines (
    Id BIGINT PRIMARY KEY AUTO_INCREMENT,
    PayRunEmployeeId INT NOT NULL,
    PayRunId INT NOT NULL,
    EmployeeId INT NOT NULL,
    ComponentCode VARCHAR(80) NOT NULL,
    Name VARCHAR(180) NOT NULL DEFAULT '',
    Category VARCHAR(80) NOT NULL DEFAULT '',
    MonthlyAmount DECIMAL(18,4) NOT NULL DEFAULT 0,
    Amount DECIMAL(18,4) NOT NULL DEFAULT 0,
    ProRata BOOLEAN NOT NULL DEFAULT FALSE,
    SortOrder INT NOT NULL DEFAULT 0,
    UNIQUE KEY UX_PayRunEmployeeLines_Row_Component (PayRunEmployeeId, ComponentCode, SortOrder)
);

-- Data backfill is also performed by API startup for safety.
-- Do not migrate Tax Engine tables or PayrollSetups.statutory/tax blocks in this script.
