-- Generic salary component engine rollout
-- Date: 2026-06-28
--
-- No table ALTER is required for this change.
-- Existing PayrollSetups.SetupJson already stores:
--   salaryComponents
--   salaryStructures
-- Existing Employees already store:
--   SalaryStructureId
--   AnnualCtc
--   SalaryJson
--
-- Team note:
-- Components are now resolved from setup JSON by code/formula at pay-run time.
-- Old calculation labels remain backward compatible:
--   Percentage of CTC       -> Formula
--   Percentage of Component -> Formula
--   Balancing Amount        -> Residual / Balancing
--   Manual Override         -> Manual / Variable
--
-- Nothing to execute unless a future migration adds physical columns.
