import { useEffect, useState } from 'react'
import DataTable from '../components/DataTable'
import { Chk, F, Sel } from '../components/FormPrimitives'
import { demoComponents, demoStructures, employee0, setup0 } from '../data/payrollDefaults'
import { getClients, getEmployees } from '../services/payrollService'
import { getDropdowns, getSetup, getWorkLocations, saveEmployee as persistEmployee } from '../services/settingsService'
import type { Client, Component, Drop, Employee, Setup, Structure, WorkLocation } from '../types/payroll'
import { calculateSalaryJson } from '../utils/salary'

export default function EmployeePage() {
  const [clients, setClients] = useState<Client[]>([]), [locations, setLocations] = useState<WorkLocation[]>([]), [drops, setDrops] = useState<Drop[]>([]), [setup, setSetup] = useState<Setup>(setup0)
  const [employees, setEmployees] = useState<Employee[]>([]), [employee, setEmployee] = useState(employee0), [employeeTab, setEmployeeTab] = useState<'Basics' | 'Salary' | 'Personal' | 'Payment'>('Basics')
  const chosenStructure = setup.salaryStructures.find(item => String(item.id) === employee.salaryStructureId)
  const employeeSalary = JSON.parse(employee.salaryJson || '{}') as Record<string, string>
  const structureComponents = setup.salaryComponents.filter(component => component.active && chosenStructure?.lines.some(line => line.componentId === String(component.id))).sort((a, b) => Number(a.priority) - Number(b.priority))
  const deps = drops.filter(item => item.type === 'Department' && item.isActive).map(item => item.value), desigs = drops.filter(item => item.type === 'Designation' && item.isActive).map(item => item.value)

  const load = async () => {
    const [clientRows, locationRows, dropdownRows, employeeRows, rawSetup] = await Promise.all([getClients(), getWorkLocations(), getDropdowns(), getEmployees(), getSetup(setup0)])
    setClients(clientRows); setLocations(locationRows); setDrops(dropdownRows); setEmployees(employeeRows)
    setSetup({ ...setup0, ...rawSetup, salaryComponents: rawSetup.salaryComponents?.length ? rawSetup.salaryComponents : demoComponents, salaryStructures: rawSetup.salaryStructures?.length ? rawSetup.salaryStructures : demoStructures })
  }

  useEffect(() => { void load() }, [])
  const calcSalary = (ctc: number, salaryStructure = chosenStructure) => calculateSalaryJson(ctc, setup.salaryComponents, salaryStructure)
  const empLine = (componentId: string, value: string) => { const lines = JSON.parse(employee.salaryJson || '{}'); lines[componentId] = value; setEmployee({ ...employee, salaryJson: JSON.stringify(lines), annualCtc: Number(chosenStructure?.annualCtc || employee.annualCtc) }) }
  const empMonthly = (component: Component) => Number(employeeSalary[String(component.id)] || 0)
  const applyStructure = (id: string) => { const selectedId = id.split(':')[0]; const selectedStructure = setup.salaryStructures.find(item => String(item.id) === selectedId); const ctc = Number(selectedStructure?.annualCtc || employee.annualCtc || 0); setEmployee({ ...employee, salaryStructureId: selectedId, annualCtc: ctc, salaryJson: calcSalary(ctc, selectedStructure) }) }
  const applyCtc = (ctc: number) => setEmployee({ ...employee, annualCtc: ctc, salaryJson: calcSalary(ctc) })
  const applyClient = (value: string) => { const clientId = Number(value.split(':')[0] || 0); const selectedStructure = setup.salaryStructures.find(item => item.clientId.startsWith(String(clientId))) ?? setup.salaryStructures[0]; const ctc = Number(selectedStructure?.annualCtc || employee.annualCtc || 0); setEmployee({ ...employee, clientId, salaryStructureId: selectedStructure ? String(selectedStructure.id) : '', annualCtc: ctc, salaryJson: selectedStructure ? calcSalary(ctc, selectedStructure) : '{}' }) }
  const saveEmployee = async () => { const response = await persistEmployee(employee); if (response.ok) { setEmployee(employee0); await load() } }

  return <EmployeePanel employee={employee} setEmployee={setEmployee} employeeTab={employeeTab} setEmployeeTab={setEmployeeTab} clients={clients} locations={locations} templates={setup.salaryStructures} deps={deps} desigs={desigs} applyClient={applyClient} applyStructure={applyStructure} applyCtc={applyCtc} structureComponents={structureComponents} employeeSalary={employeeSalary} empLine={empLine} empMonthly={empMonthly} saveEmployee={saveEmployee} employees={employees} />
}

function EmployeePanel(p: { employee: Employee; setEmployee: (employee: Employee) => void; employeeTab: 'Basics' | 'Salary' | 'Personal' | 'Payment'; setEmployeeTab: (tab: 'Basics' | 'Salary' | 'Personal' | 'Payment') => void; clients: Client[]; locations: WorkLocation[]; templates: Structure[]; deps: string[]; desigs: string[]; applyClient: (value: string) => void; applyStructure: (value: string) => void; applyCtc: (value: number) => void; structureComponents: Component[]; employeeSalary: Record<string, string>; empLine: (id: string, value: string) => void; empMonthly: (component: Component) => number; saveEmployee: () => void; employees: Employee[] }) {
  const personal = JSON.parse(p.employee.personalJson || '{}'), payment = JSON.parse(p.employee.paymentJson || '{}')
  const setPersonal = (key: string, value: string) => p.setEmployee({ ...p.employee, personalJson: JSON.stringify({ ...personal, [key]: value }) })
  const setPayment = (key: string, value: string) => p.setEmployee({ ...p.employee, paymentJson: JSON.stringify({ ...payment, [key]: value }) })
  return <section className="card employee-card"><header><i className="blue">?</i><div><h3>Employee master</h3><p>Client linked profile, salary template and payroll details.</p></div></header><div className="tabs">{(['Basics', 'Salary', 'Personal', 'Payment'] as const).map(item => <button type="button" className={p.employeeTab === item ? 'on' : ''} onClick={() => p.setEmployeeTab(item)} key={item}>{item}</button>)}</div>
    {p.employeeTab === 'Basics' && <div className="grid"><F l="Client"><Sel v={String(p.employee.clientId || '')} set={p.applyClient} a={p.clients.map(item => `${item.id}:${item.name}`)} /></F><F l="Employee code"><input value={p.employee.employeeCode} onChange={event => p.setEmployee({ ...p.employee, employeeCode: event.target.value })} /></F><F l="First name"><input value={p.employee.firstName} onChange={event => p.setEmployee({ ...p.employee, firstName: event.target.value })} /></F><F l="Last name"><input value={p.employee.lastName} onChange={event => p.setEmployee({ ...p.employee, lastName: event.target.value })} /></F><F l="Gender"><Sel v={p.employee.gender} set={value => p.setEmployee({ ...p.employee, gender: value })} a={['Male', 'Female', 'Other']} /></F><F l="Date of joining"><input type="date" value={p.employee.dateOfJoining} onChange={event => p.setEmployee({ ...p.employee, dateOfJoining: event.target.value })} /></F><F l="Work email"><input value={p.employee.workEmail} onChange={event => p.setEmployee({ ...p.employee, workEmail: event.target.value })} /></F><F l="Department"><Sel v={p.employee.department} set={value => p.setEmployee({ ...p.employee, department: value })} a={p.deps} /></F><F l="Designation"><Sel v={p.employee.designation} set={value => p.setEmployee({ ...p.employee, designation: value })} a={p.desigs} /></F><F l="Work location"><Sel v={String(p.employee.workLocationId || '')} set={value => p.setEmployee({ ...p.employee, workLocationId: Number(value.split(':')[0] || 0) })} a={p.locations.map(item => `${item.id}:${item.name}`)} /></F><Chk l="Portal access" v={p.employee.portalAccess} set={value => p.setEmployee({ ...p.employee, portalAccess: value })} /><Chk l="Active" v={p.employee.isActive} set={value => p.setEmployee({ ...p.employee, isActive: value })} /></div>}
    {p.employeeTab === 'Salary' && <><div className="grid"><F l="Salary template"><Sel v={p.employee.salaryStructureId} set={p.applyStructure} a={p.templates.filter(item => !p.employee.clientId || item.clientId.startsWith(String(p.employee.clientId))).map(item => `${item.id}:${item.name}`)} /></F><F l="Annual CTC"><input value={p.employee.annualCtc} onChange={event => p.applyCtc(Number(event.target.value.replace(/\D/g, '')))} /></F></div><div className="template-canvas employee-salary"><div className="template-line employee-line head"><span>Type</span><span>Code</span><span>Name</span><span>Monthly</span><span>Annual</span><span>Override</span></div>{p.structureComponents.length ? p.structureComponents.map(component => <div className="template-line employee-line" key={component.id}><span className={`pill ${component.category.toLowerCase()}`}>{component.category}</span><b>{component.code}</b><strong>{component.name}</strong><output>Rs {Math.round(p.empMonthly(component)).toLocaleString('en-IN')}</output><output>Rs {Math.round(p.empMonthly(component) * 12).toLocaleString('en-IN')}</output><input value={p.employeeSalary[String(component.id)] ?? ''} onChange={event => p.empLine(String(component.id), event.target.value.replace(/[^\d.-]/g, ''))} /></div>) : <p>Select client and salary template.</p>}</div></>}
    {p.employeeTab === 'Personal' && <div className="grid"><F l="Date of birth"><input type="date" value={personal.dob || ''} onChange={event => setPersonal('dob', event.target.value)} /></F><F l="PAN"><input value={personal.pan || ''} onChange={event => setPersonal('pan', event.target.value.toUpperCase())} /></F><F l="Aadhaar"><input value={personal.aadhaar || ''} onChange={event => setPersonal('aadhaar', event.target.value.replace(/\D/g, '').slice(0, 12))} /></F><F l="Mobile"><input value={personal.mobile || ''} onChange={event => setPersonal('mobile', event.target.value)} /></F><F l="Address" w><input value={personal.address || ''} onChange={event => setPersonal('address', event.target.value)} /></F></div>}
    {p.employeeTab === 'Payment' && <div className="grid"><F l="Bank"><input value={payment.bank || ''} onChange={event => setPayment('bank', event.target.value)} /></F><F l="Account no"><input value={payment.account || ''} onChange={event => setPayment('account', event.target.value)} /></F><F l="IFSC"><input value={payment.ifsc || ''} onChange={event => setPayment('ifsc', event.target.value.toUpperCase())} /></F><F l="Payment mode"><Sel v={payment.mode || ''} set={value => setPayment('mode', value)} a={['Bank Transfer', 'Cheque', 'Cash']} /></F></div>}
    <div className="actions"><p>Leave and attendance will be added later.</p><button type="button" onClick={p.saveEmployee}>Save employee</button></div><DataTable rows={p.employees} onEdit={p.setEmployee} columns={[{ key: 'employeeCode', label: 'Code' }, { key: 'firstName', label: 'First Name' }, { key: 'lastName', label: 'Last Name' }, { key: 'clientId', label: 'Client' }, { key: 'department', label: 'Department' }, { key: 'designation', label: 'Designation' }, { key: 'isActive', label: 'Status', render: item => item.isActive ? 'Active' : 'Inactive' }]} /></section>
}
