using Dapper;
using MySqlConnector;
using Payroll.API.Repositories;
using Xunit;

namespace Payroll.API.Tests.Repositories;

public class RecruitmentNumberSequenceTests
{
    [LocalInterviewDatabaseFact]
    public async Task RfrNumbersSurviveGapsDeletionAndConcurrentAllocations()
    {
        var connection = new MySqlConnectionStringBuilder(Environment.GetEnvironmentVariable("HRMS_INTERNAL_INTERVIEW_TEST_CONNECTION")
            ?? throw new InvalidOperationException("An explicit loopback test connection is required."));
        Assert.Contains(connection.Server, new[] { "localhost", "127.0.0.1", "::1" });
        connection.Database = "";
        await using var owner = new MySqlConnection(connection.ConnectionString);
        await owner.OpenAsync();
        var database = "hrms_rfr_test_" + Guid.NewGuid().ToString("N");
        await owner.ExecuteAsync($"CREATE DATABASE `{database}`");
        try
        {
            connection.Database = database;
            await using var db = new MySqlConnection(connection.ConnectionString);
            await db.OpenAsync();
            await db.ExecuteAsync(@"CREATE TABLE clients (Id INT PRIMARY KEY, Code VARCHAR(80));
CREATE TABLE recruitment_requisitions (RfrNumber VARCHAR(80) UNIQUE, CreatedAt DATETIME);
CREATE TABLE recruitment_number_sequences (Id INT PRIMARY KEY AUTO_INCREMENT,ClientId INT NOT NULL,SeriesCode VARCHAR(30) NOT NULL,LastNumber INT NOT NULL,UNIQUE KEY (ClientId,SeriesCode));
INSERT INTO clients VALUES (20,'UIDAI'),(21,'OTHER');");
            var prefix = $"RFR-UIDAI-{DateTime.UtcNow.Year}-";
            await db.ExecuteAsync("INSERT INTO recruitment_requisitions VALUES (@First,'2020-01-01'),(@Third,'2020-01-01')",
                new { First = prefix + "00001", Third = prefix + "00003" });
            Assert.Equal(prefix + "00004", await RecruitmentRepository.NextRfrNumberAsync(db, 20));
            await db.ExecuteAsync("DELETE FROM recruitment_requisitions");
            Assert.Equal(prefix + "00005", await RecruitmentRepository.NextRfrNumberAsync(db, 20));

            var allocated = await Task.WhenAll(Enumerable.Range(0, 16).Select(async _ =>
            {
                await using var concurrent = new MySqlConnection(connection.ConnectionString);
                await concurrent.OpenAsync();
                return await RecruitmentRepository.NextRfrNumberAsync(concurrent, 20);
            }));
            Assert.Equal(Enumerable.Range(6, 16).Select(i => $"{prefix}{i:D5}"), allocated.OrderBy(x => x));
            Assert.Equal($"RFR-OTHER-{DateTime.UtcNow.Year}-00001", await RecruitmentRepository.NextRfrNumberAsync(db, 21));

            // Existing/imported numbers ahead of the counter must advance it safely.
            await db.ExecuteAsync("INSERT INTO recruitment_requisitions VALUES (@Number,'2020-01-01')", new { Number = prefix + "00100" });
            Assert.Equal(prefix + "00101", await RecruitmentRepository.NextRfrNumberAsync(db, 20));
        }
        finally
        {
            // Only the disposable database generated by this test is removed.
            await owner.ExecuteAsync($"DROP DATABASE `{database}`");
        }
    }
}
