export type User = {
  id: number
  email: string
  displayName: string
  roles: string[]
  permissions: string[]
  mustChangePassword: boolean
  employeeId?: number
  clientId?: number
}

export type OrganizationBrand = { name: string; logoDataUrl: string }

export type View = 'Dashboard' | 'My Profile' | 'Leave' | 'Travel' | 'Expense' | 'Recruitment' | 'Attendance' | 'Attendance Review' | 'Pay' | 'Tax' | 'My Tasks' | 'Team' | 'Approvals'
export type LoadState = 'loading' | 'ready' | 'error'

export type Task = { id: number; instanceId: number; resourceType: string; resourceId: string; stageName: string; payloadJson: string; status?: string; comment?: string; createdAt: string; actionedAt?: string }
export type ProfileData = { clientId: number; employeeCode: string; firstName: string; lastName: string; workEmail: string; dateOfBirth: string; mobile: string; panNumber: string; aadhaarNumber: string; address: string; correspondenceAddress: string; permanentAddress: string; city: string; district: string; state: string; bankName: string; bankAccountNo: string; ifscCode: string; paymentMode: string; department: string; designation: string; dateOfJoining: string; workLocation: string; attendanceOffice: string; reportingManager: string; canEdit: boolean; travelExpenseEnabled: boolean }
export type FeatureAccess = { travelExpenseEnabled: boolean }
export type SaveProfileData = Omit<ProfileData, 'clientId' | 'employeeCode' | 'department' | 'designation' | 'dateOfJoining' | 'workLocation' | 'attendanceOffice' | 'reportingManager' | 'canEdit' | 'travelExpenseEnabled'>
export type AttachmentFieldConfiguration = { id: number; fieldKey: string; fieldLabel: string; helpText: string; attributeName: string; dataClassification: string; isRequired: boolean; allowMultiple: boolean; maximumFileCount: number; allowedExtensionsJson: string; maximumFileSizeBytes: number; ownerCanView: boolean; ownerCanUpload: boolean; ownerCanReplace: boolean; ownerCanDelete: boolean; requiresDocumentNumber: boolean; requiresIssueDate: boolean; requiresExpiryDate: boolean; versioningEnabled: boolean }
export type EntityAttachment = { publicId: string; fieldConfigurationId: number; originalFileName: string; detectedMimeType: string; fileSizeBytes: number; versionNumber: number; documentNumber: string; issueDate?: string | null; expiryDate?: string | null; verificationStatus: string; rejectionReason: string; uploadedAtUtc: string }
export type AttachmentAccessTicket = { url: string; expiresAtUtc: string }
export type LeaveBalance = { leaveCode: string; leaveType: string; balance: number; balanceDate: string; allowHalfDay: boolean }
export type LeaveRequest = { id: number; leaveCode: string; leaveType: string; fromDate: string; toDate: string; dayType: string; days: number; reason: string; status: string; createdAt: string }
export type TravelCity = { fromLocation: string; toLocation: string; travelMode: string; travelClass: string; remarks: string; startDateTime?: string; endDateTime?: string }
export type TravelAccommodation = { city: string; checkInDateTime?: string; checkOutDateTime?: string; occupancy: string; roomPreference: string; remarks: string }
export type LocalTravelDetail = { city: string; travelDateTime?: string; fromLocation: string; toLocation: string; travelMode: string; remarks: string }
export type TravelRequest = { id: number; requestNumber: string; requestDate: string; employeeName: string; department: string; designation: string; reportingManager: string; purpose: string; customer: string; project: string; costCenter: string; travelScope: 'Domestic' | 'International'; travelType: string; priority: string; fromLocation: string; toLocation: string; legs: TravelCity[]; accommodationDetails: TravelAccommodation[]; localTravelDetails: LocalTravelDetail[]; startDateTime: string; endDateTime: string; estimatedCost: number; policyId?: number; policyName: string; travelMode: string; accommodationRequired: boolean; localConveyanceRequired: boolean; advanceRequired: boolean; advanceAmount: number; remarks: string; status: string; policyValidationJson: string; cancellationReason: string; cancellationDate?: string; cancellationStatus: string; createdAt: string; updatedAt: string }
export type SaveTravelRequest = { id: number; purpose: string; customer: string; project: string; costCenter: string; travelScope: 'Domestic' | 'International'; travelType: string; priority: string; fromLocation: string; toLocation: string; cities: TravelCity[]; accommodationDetails: TravelAccommodation[]; localTravelDetails: LocalTravelDetail[]; startDateTime: string; endDateTime: string; estimatedCost: number; travelMode: string; accommodationRequired: boolean; localConveyanceRequired: boolean; advanceRequired: boolean; advanceAmount: number; remarks: string }
export type TravelOptions = { policyId?: number; policyName: string; clientName: string; travelModes: string[]; localTravelModes: string[]; travelTypes: string[]; priorities: string[]; locations: string[]; travelClasses: string[]; showTripDetails: boolean; showAccommodationDetails: boolean; showLocalTravelDetails: boolean; validationMessages: string[] }
export type TravelDashboard = { draftRequests: number; pendingApproval: number; approved: number; rejected: number; upcomingTravel: number; cancelledTrips: number }
export type ExpenseLine = { id?: number; claimId?: number; expenseDate: string; categoryId: number; categoryCode: string; categoryName: string; subCategory: string; vendorName: string; billNumber: string; invoiceNumber: string; amount: number; currency: string; exchangeRate: number; gstAmount: number; approvedAmount: number; costCenter: string; project: string; customer: string; location: string; paymentMethod: string; receiptAttached: boolean; receiptFileName: string; description: string; status: string; validationJson?: string }
export type ExpenseClaim = { id: number; claimNumber: string; claimDate: string; employeeName: string; department: string; designation: string; travelRequestId?: number; travelRequestNumber: string; expenseType: string; purpose: string; customer: string; project: string; costCenter: string; currency: string; totalClaimAmount: number; totalApprovedAmount: number; totalGstAmount: number; payrollStatus: string; payrollRunId?: number; reimbursementComponentCode: string; status: string; policyValidationJson: string; remarks: string; submittedAt?: string; createdAt: string; updatedAt: string; lines: ExpenseLine[] }
export type SaveExpenseClaim = { id: number; travelRequestId?: number; expenseType: string; purpose: string; customer: string; project: string; costCenter: string; currency: string; remarks: string; lines: ExpenseLine[] }
export type ExpenseCategoryOption = { id: number; clientId: number; parentId?: number; parentName: string; expenseType: string; isClaimHeader: boolean; categoryCode: string; categoryName: string; receiptMandatory: boolean; gstApplicable: boolean; dailyLimit?: number; maximumClaim?: number; requiresFinanceApproval: boolean; requiresManagerApproval: boolean }
export type ExpenseTravelOption = { id: number; requestNumber: string; purpose: string; customer: string; project: string; costCenter: string; startDateTime: string; endDateTime: string; travelMode: string; accommodationRequired: boolean; localConveyanceRequired: boolean }
export type ExpenseOptions = { clientName: string; policyId?: number; policyName: string; headers: ExpenseCategoryOption[]; categories: ExpenseCategoryOption[]; travelRequests: ExpenseTravelOption[]; currencies: string[]; locations: string[]; paymentMethods: string[]; validationMessages: string[] }
export type ExpenseDashboard = { draftClaims: number; pendingApproval: number; approved: number; rejected: number; pendingPayroll: number; approvedAmount: number }
export type RecruitmentRequisition = { id: number; rfrNumber: string; requestDate: string; requestedByName: string; clientId: number; clientName: string; branchId: number; branchName: string; businessUnit: string; department: string; costCenter: string; positionTitle: string; positionCategory: string; employmentType: string; hiringType: string; numberOfOpenings: number; isReplacement: boolean; replacementEmployeeId?: number; replacementEmployeeName: string; targetJoiningDate?: string; jobLocation: string; workMode: string; project: string; budgetAvailable: boolean; budgetAmount: number; hiringPriority: string; businessJustification: string; reasonForHiring: string; experienceRange: string; qualification: string; requiredSkills: string; preferredSkills: string; certifications: string; languages: string; salaryMin: number; salaryMax: number; currency: string; benefits: string; status: string; workflowInstanceId?: number; openPositionId?: number; submittedAt?: string; createdAt: string; updatedAt: string }
export type SaveRecruitmentRequisition = { id: number; branchId: number; businessUnit: string; department: string; costCenter: string; positionTitle: string; positionCategory: string; employmentType: string; hiringType: string; numberOfOpenings: number; isReplacement: boolean; replacementEmployeeId?: number; targetJoiningDate?: string; jobLocation: string; workMode: string; clientId?: number; project: string; budgetAvailable: boolean; budgetAmount: number; hiringPriority: string; businessJustification: string; reasonForHiring: string; experienceRange: string; qualification: string; requiredSkills: string; preferredSkills: string; certifications: string; languages: string; salaryMin: number; salaryMax: number; currency: string; benefits: string }
export type RecruitmentOptions = { moduleEnabled: boolean; enabled: boolean; allowReplacementHiring: boolean; enableInternalHiring: boolean; enableReferralHiring: boolean; displayName: string; clientName: string; positionCategories: string[]; hiringTypes: string[]; employmentTypes: string[]; departments: string[]; designations: string[]; grades: string[]; workLocations: string[]; businessUnits: string[]; costCenters: string[]; experienceRanges: string[]; budgetAmounts: string[]; priorities: string[]; employees: { id: number; employeeCode: string; employeeName: string; department: string; designation: string }[]; validationMessages: string[] }
export type RecruitmentDashboard = { drafts: number; pendingApproval: number; approved: number; rejected: number; returned: number; withdrawn: number; openPositions: number }
export type RecruitmentInternalOpening = { positionId: number; positionCode: string; positionTitle: string; department: string; jobLocation: string; employmentType: string; hiringType: string; experienceRange: string; requiredSkills: string; targetJoiningDate?: string; campaignName: string; referralReward: number; endDate: string }
export type RecruitmentEmployeeReferral = { id: number; candidateId?: number | null; applicationId?: number | null; positionId: number; positionCode: string; positionTitle: string; candidateName: string; candidateEmail: string; candidatePhone: string; relationship: string; remarks: string; status: string; createdAt: string }
export type SaveEmployeeReferral = { positionId: number; candidateName: string; candidateEmail: string; candidatePhone: string; relationship: string; remarks: string }
export type WorkflowTrail = { instanceId?: number; workflowCode: string; workflowName: string; resourceType: string; matchScope: string; status: string; createdAt?: string; completedAt?: string; events: WorkflowTrailItem[] }
export type WorkflowTrailItem = { stageName: string; action: string; actor: string; comment: string; createdAt: string; isPending: boolean }
export type DailyAttendance = { attendanceDate: string; status: string; payableValue: number; remarks: string }
export type AttendanceGroup = { id: number; clientId: number; clientName: string; policyBatchId?: string; name: string; workLocationId: number; workLocationName: string; department: string; designation: string; workWeek: string; attendanceCycleStartDay: number; attendanceCycleEndDay: number; payrollReportGenerationDay: number; employeeIds: number[]; employeeNames: string; employeeCount: number; isActive: boolean }
export type ManagedMonthlyAttendance = { employeeId: number; employeeCode: string; employeeName: string; department: string; workLocationId: number; workingDays: number; presentDays: number; payableDays: number; lopDays: number }
export type ManagedDailyAttendance = { id: number; clientId: number; employeeId: number; attendanceDate: string; status: string; payableValue: number; checkInTime?: string | null; checkOutTime?: string | null; totalHours: number; remarks: string }
export type EmployeeMonthlyAttendance = ManagedMonthlyAttendance & { attendanceGroupId?: number | null; attendanceGroupName: string; workWeek: string; attendanceCycleStartDay?: number | null; attendanceCycleEndDay?: number | null; payrollReportGenerationDay?: number | null; month: string; sourceType: string; remarks: string }
export type EmployeeDailyAttendance = ManagedDailyAttendance
export type AttendanceBatchJobState = 'Queued' | 'Processing' | 'Completed' | 'Failed'
export type AttendanceBatchJobStatus = { jobId: string; clientId: number; month: string; state: AttendanceBatchJobState; stage: string; totalRows: number; completedRows: number; savedRows: number; errors: string[] }
export type AttendanceBatchJob = AttendanceBatchJobStatus
export type Drop = { id: number; clientId: number; type: string; value: string; configJson?: string; isActive: boolean }
export type AttendanceSettings = { id: number; clientId: number; checkInTime: string; checkOutTime: string; workingHoursCalculation: 'First check-in and last check-out' | 'Every valid check-in and check-out'; minimumHoursForHalfDay: number; minimumHoursForFullDay: number; maximumHoursAllowedForFullDay: number; allowRegularizationRequests: boolean; regularizationWindow: 'Anytime' | 'Limited by past days'; pastDaysAllowed: number; restrictRegularizationRequestsPerMonth: boolean; maxRegularizationRequestsPerMonth: number }
export type LeaveAttendancePreferences = { id: number; clientId: number; workLocationId?: number | null; workLocationName?: string; workWeek: string; attendanceCycleStartDay: number; attendanceCycleEndDay: number; payrollReportGenerationDay: number; includeLeaveEncashmentInPayRun: boolean; leaveEncashmentSalaryComponentId?: number | null }
export type ClientAttendanceSchedule = { workWeek: string; salaryDays: string; fixedDays: string; payDay: string; firstPayPeriod: string }
export type ManagedAttendanceHoliday = { id: number; clientId: number; name: string; holidayType: 'Holiday' | 'Restricted Holiday'; startDate: string; endDate: string; description: string; allLocations: boolean; workLocationIds: number[]; workLocations: string }
export type EmployeeLeaveBalanceSummary = { employeeId: number; leaveTypeId: number; leaveTypeCode: string; leaveTypeName: string; balance: number; balanceDate: string; allowNegativeLeaveBalance: boolean }
export type AttendanceReviewContext = { settings: AttendanceSettings; schedule: ClientAttendanceSchedule; preferences: LeaveAttendancePreferences; holidays: ManagedAttendanceHoliday[]; leaveBalances: EmployeeLeaveBalanceSummary[] }
export type LeaveType = { id: number; clientId: number; name: string; code: string; type: 'Paid' | 'Unpaid'; allowNegativeLeaveBalance: boolean; allowHalfDay: boolean; attendanceAction: 'Mark as leave' | 'Mark as present'; isActive: boolean }
export type AttendanceSummary = { presentDays: number; payableDays: number; totalWorkingDays: number }
export type Holiday = { name: string; startDate: string; endDate: string }
export type Birthday = { name: string; department: string }
export type CalendarDayInfo = { date: string; status: string; label: string; canApply: boolean; leave?: { leaveType: string; status: string }; holiday?: { name: string } }
export type Payslip = { payRunId: number; payPeriod: string; payDate: string; runStatus: string; grossPay: number; statutoryDeductions: number; oneTimeDeductions: number; netPay: number; paymentStatus: string; paymentDate?: string }
export type PayslipDocument = { payRunId: number; payPeriod: string; employeeCode: string; fileName: string; html: string }
export type TaxPortal = { financialYear: string; enabled: boolean; defaultRegime: 'Old' | 'New'; selectedRegime?: 'Old' | 'New'; regimeStatus: string; canSelectRegime: boolean; canDeclare: boolean; canSubmitPlanned: boolean; canSubmitActual: boolean; regimeSelectionWindowOpen: boolean; plannedDeclarationWindowOpen: boolean; actualDeclarationWindowOpen: boolean; declarationRequired: boolean; declarationPhase: 'Planned' | 'Actual' | 'Closed' | 'NotRequired'; requiresApproval: boolean; regimeSelectionCutoff?: string; declarationWindowStart?: string; declarationWindowEnd?: string; plannedDeclarationStart?: string; plannedDeclarationEnd?: string; actualDeclarationStart?: string; actualDeclarationEnd?: string; poiProcessingMonth?: string; message: string; sections: TaxDeclarationSection[]; finalAdjustments: TaxFinalAdjustmentInfo[] }
export type TaxDeclarationSection = { declarationId?: number; sectionId: number; code: string; name: string; regime: 'Old' | 'New' | 'Both'; limitAmount?: number; proofRequired: boolean; requiresApproval: boolean; declaredAmount: number; plannedAmount: number; actualAmount: number; approvedAmount?: number; status: string; remarks: string }
export type TaxFinalAdjustmentInfo = { label: string; valueType: 'Percent' | 'Fixed'; value: number }
