import { useState } from 'react'
import { saveClient } from '../services/settingsService'
import { useToast } from './ToastProvider'

type Client = { id: number; name: string; code: string; contactPerson: string; email: string; phone: string; address: string; payScheduleJson: string; isActive: boolean }
type Schedule = { workWeek: string; salaryDays: string; fixedDays: string; payDay: string; firstPayPeriod: string }
const empty: Schedule = { workWeek: 'Monday - Friday', salaryDays: 'Actual days', fixedDays: '30', payDay: 'Last working day', firstPayPeriod: new Date().toISOString().slice(0, 7) }
const read = (client: Client): Schedule => { try { return { ...empty, ...JSON.parse(client.payScheduleJson || '{}') } } catch { return empty } }

export default function ClientPayScheduleManager({ clients, reload }: { clients: Client[]; reload: () => Promise<void> }) {
  const toast = useToast()
  const [clientId, setClientId] = useState(0), [schedule, setSchedule] = useState<Schedule>(empty), [message, setMessage] = useState('')
  const select = (id: number) => { const client = clients.find(row => row.id === id); setClientId(id); setSchedule(client ? read(client) : empty) }
  const save = async () => { const client = clients.find(row => row.id === clientId); if (!client) return setMessage('Select a client.'); const response = await saveClient({ ...client, payScheduleJson: JSON.stringify(schedule) }); setMessage(response.ok ? 'Schedule saved.' : 'Unable to save schedule.'); if (response.ok) { toast('Client schedule saved.'); await reload() } }
  const remove = async () => { const client = clients.find(row => row.id === clientId); if (!client || !window.confirm('Delete this client schedule?')) return; const response = await saveClient({ ...client, payScheduleJson: '{}' }); setMessage(response.ok ? 'Schedule deleted.' : 'Unable to delete schedule.'); if (response.ok) { setSchedule(empty); await reload() } }
  return <section className="schedule-crud"><div className="grid"><label><span>Client</span><select value={clientId} onChange={event => select(Number(event.target.value))}><option value="0">Select client</option>{clients.filter(client => client.isActive).map(client => <option value={client.id} key={client.id}>{client.name}</option>)}</select></label><label><span>Work week</span><select value={schedule.workWeek} onChange={event => setSchedule({ ...schedule, workWeek: event.target.value })}><option>Monday - Friday</option><option>Monday - Saturday</option><option>All days</option></select></label><label><span>Salary days</span><select value={schedule.salaryDays} onChange={event => setSchedule({ ...schedule, salaryDays: event.target.value })}><option>Actual days</option><option>Fixed days</option></select></label><label><span>Fixed days</span><input value={schedule.fixedDays} onChange={event => setSchedule({ ...schedule, fixedDays: event.target.value.replace(/\D/g, '').slice(0, 2) })} /></label><label><span>Pay day</span><select value={schedule.payDay} onChange={event => setSchedule({ ...schedule, payDay: event.target.value })}><option>Last working day</option><option>Last day of month</option><option>1st of next month</option><option>5th of next month</option></select></label><label><span>First period</span><input type="month" value={schedule.firstPayPeriod} onChange={event => setSchedule({ ...schedule, firstPayPeriod: event.target.value })} /></label></div><div className="schedule-actions"><button type="button" onClick={() => void save()}>Save schedule</button><button type="button" className="secondary" onClick={() => void remove()}>Delete schedule</button><small>{message}</small></div><div className="data-table"><table><thead><tr><th>Client</th><th>Work week</th><th>Salary days</th><th>Pay day</th><th /></tr></thead><tbody>{clients.filter(client => client.payScheduleJson && client.payScheduleJson !== '{}').map(client => { const value = read(client); return <tr key={client.id}><td>{client.name}</td><td>{value.workWeek}</td><td>{value.salaryDays === 'Fixed days' ? `Fixed: ${value.fixedDays}` : value.salaryDays}</td><td>{value.payDay}</td><td><button type="button" onClick={() => select(client.id)}>Edit</button></td></tr> })}</tbody></table></div></section>
}
