import type { Dispatch, SetStateAction } from 'react'
import { Button, Card, Checkbox, Input, InputNumber } from 'antd'
import type { RecruitmentCandidateExperience, RecruitmentCandidateEducation, RecruitmentCandidateCertification } from '../types/payroll'
export type CandidateProfileDraft = { experience: RecruitmentCandidateExperience[]; education: RecruitmentCandidateEducation[]; certifications: RecruitmentCandidateCertification[] }
const experience0: RecruitmentCandidateExperience = { id: 0, candidateId: 0, employer: '', jobTitle: '', startDate: null, endDate: null, isCurrent: false, description: '', displayOrder: 100 }
const education0: RecruitmentCandidateEducation = { id: 0, candidateId: 0, qualification: '', institution: '', specialization: '', completionYear: null, score: '', displayOrder: 100 }
const certification0: RecruitmentCandidateCertification = { id: 0, candidateId: 0, certificationName: '', issuer: '', issueDate: null, expiryDate: null, credentialId: '' }

export default function CandidateProfileFields({ profileDraft, setProfileDraft, candidateId }: { profileDraft: CandidateProfileDraft; setProfileDraft: Dispatch<SetStateAction<CandidateProfileDraft | null>>; candidateId: number }) {
  const patchExperience = (index: number, patch: Partial<RecruitmentCandidateExperience>) => setProfileDraft(current => current ? ({ ...current, experience: current.experience.map((row, rowIndex) => rowIndex === index ? { ...row, ...patch } : row) }) : current)
  const patchEducation = (index: number, patch: Partial<RecruitmentCandidateEducation>) => setProfileDraft(current => current ? ({ ...current, education: current.education.map((row, rowIndex) => rowIndex === index ? { ...row, ...patch } : row) }) : current)
  const patchCertification = (index: number, patch: Partial<RecruitmentCandidateCertification>) => setProfileDraft(current => current ? ({ ...current, certifications: current.certifications.map((row, rowIndex) => rowIndex === index ? { ...row, ...patch } : row) }) : current)

  return <div className="candidate-profile-editor">
      <Card size="small" title="Experience" extra={<Button size="small" onClick={() => setProfileDraft({ ...profileDraft, experience: [...profileDraft.experience, { ...experience0, candidateId: candidateId }] })}>Add experience</Button>}>{profileDraft.experience.map((row, index) => <div className="candidate-profile-row" key={`experience-${index}`}><Input placeholder="Employer" value={row.employer} onChange={event => patchExperience(index, { employer: event.target.value })} /><Input placeholder="Job title" value={row.jobTitle} onChange={event => patchExperience(index, { jobTitle: event.target.value })} /><Input type="date" value={row.startDate?.slice(0, 10) || ''} onChange={event => patchExperience(index, { startDate: event.target.value || null })} /><Input type="date" disabled={row.isCurrent} value={row.endDate?.slice(0, 10) || ''} onChange={event => patchExperience(index, { endDate: event.target.value || null })} /><Checkbox checked={row.isCurrent} onChange={event => patchExperience(index, { isCurrent: event.target.checked, endDate: event.target.checked ? null : row.endDate })}>Current</Checkbox><Button danger size="small" onClick={() => setProfileDraft({ ...profileDraft, experience: profileDraft.experience.filter((_, rowIndex) => rowIndex !== index) })}>Remove</Button></div>)}</Card>
      <Card size="small" title="Education" extra={<Button size="small" onClick={() => setProfileDraft({ ...profileDraft, education: [...profileDraft.education, { ...education0, candidateId: candidateId }] })}>Add education</Button>}>{profileDraft.education.map((row, index) => <div className="candidate-profile-row education" key={`education-${index}`}><Input placeholder="Qualification" value={row.qualification} onChange={event => patchEducation(index, { qualification: event.target.value })} /><Input placeholder="Institution" value={row.institution} onChange={event => patchEducation(index, { institution: event.target.value })} /><Input placeholder="Specialization" value={row.specialization} onChange={event => patchEducation(index, { specialization: event.target.value })} /><InputNumber placeholder="Year" min={1950} max={2100} value={row.completionYear} onChange={value => patchEducation(index, { completionYear: value ? Number(value) : null })} /><Input placeholder="Score / grade" value={row.score} onChange={event => patchEducation(index, { score: event.target.value })} /><Button danger size="small" onClick={() => setProfileDraft({ ...profileDraft, education: profileDraft.education.filter((_, rowIndex) => rowIndex !== index) })}>Remove</Button></div>)}</Card>
      <Card size="small" title="Certifications" extra={<Button size="small" onClick={() => setProfileDraft({ ...profileDraft, certifications: [...profileDraft.certifications, { ...certification0, candidateId: candidateId }] })}>Add certification</Button>}>{profileDraft.certifications.map((row, index) => <div className="candidate-profile-row" key={`certification-${index}`}><Input placeholder="Certification" value={row.certificationName} onChange={event => patchCertification(index, { certificationName: event.target.value })} /><Input placeholder="Issuer" value={row.issuer} onChange={event => patchCertification(index, { issuer: event.target.value })} /><Input type="date" value={row.issueDate?.slice(0, 10) || ''} onChange={event => patchCertification(index, { issueDate: event.target.value || null })} /><Input type="date" value={row.expiryDate?.slice(0, 10) || ''} onChange={event => patchCertification(index, { expiryDate: event.target.value || null })} /><Input placeholder="Credential ID" value={row.credentialId} onChange={event => patchCertification(index, { credentialId: event.target.value })} /><Button danger size="small" onClick={() => setProfileDraft({ ...profileDraft, certifications: profileDraft.certifications.filter((_, rowIndex) => rowIndex !== index) })}>Remove</Button></div>)}</Card>
    </div>
}
