import { useState, type ReactNode } from 'react'
import { Alert, Form, Input, InputNumber, Select, Space } from 'antd'
import type { Client, SaveRecruitmentCandidate } from '../types/payroll'
import RecruitmentEditorDrawer from './RecruitmentEditorDrawer'
import SearchSelect, { selectOptions } from './SearchSelect'
import './RecruitmentTalentWorkspace.css'

export default function CandidateEditorDrawer({ draft, clients, onChange, onClose, onSubmit, children, guidance, saving = false }: { draft: SaveRecruitmentCandidate | null; clients: Client[]; onChange: (value: SaveRecruitmentCandidate | null) => void; onClose: () => void; onSubmit: () => void; children?: ReactNode; guidance?: string; saving?: boolean }) {
  const [noticeUnit, setNoticeUnit] = useState<'Days' | 'Months'>('Days')
  const patch = (value: Partial<SaveRecruitmentCandidate>) => draft && onChange({ ...draft, ...value })
  const noticeFactor = noticeUnit === 'Months' ? 30 : 1
  const lpa = (annualInr: number) => annualInr > 0 ? Number((annualInr / 100000).toFixed(2)) : undefined
  return <RecruitmentEditorDrawer open={!!draft} eyebrow="Talent profile" title={draft?.id ? 'Edit candidate' : 'Add candidate'} description="Maintain the candidate identity, work profile and consent details." onClose={onClose} onSubmit={onSubmit} submitLoading={saving} submitText={draft?.id ? 'Save changes' : 'Add candidate'} width="min(850px, 96vw)">{draft && <><Form layout="vertical" className="talent-form-grid">
    {guidance && <Alert className="talent-form-wide" showIcon type="warning" message="Required profile information" description={guidance} />}
    <Alert className="talent-form-wide" showIcon type="info" message="ATS profile fields" description="Current title, experience, location and qualification are used with the parsed resume and approved JD during ATS scoring. Correct any parser mismatch before running ATS." />
    <Form.Item label="Client" required><SearchSelect disabled={draft.id > 0} value={draft.clientId} onChange={value => patch({ clientId: Number(value) })} options={selectOptions(clients.map(row => ({ value: row.id, label: row.name })), 'Select client', 0)} /></Form.Item>
    <Form.Item label="First name" required><Input value={draft.firstName} onChange={event => patch({ firstName: event.target.value })} /></Form.Item><Form.Item label="Last name"><Input value={draft.lastName} onChange={event => patch({ lastName: event.target.value })} /></Form.Item>
    <Form.Item label="Email" extra="Email or phone is required before the candidate can continue through ATS."><Input value={draft.email} onChange={event => patch({ email: event.target.value })} /></Form.Item><Form.Item label="Phone"><Input value={draft.phone} onChange={event => patch({ phone: event.target.value })} /></Form.Item>
    <Form.Item label="Current company"><Input value={draft.currentCompany} onChange={event => patch({ currentCompany: event.target.value })} /></Form.Item><Form.Item label="Current title (ATS)"><Input value={draft.currentTitle} onChange={event => patch({ currentTitle: event.target.value })} /></Form.Item>
    <Form.Item label="Total experience in months (ATS)"><InputNumber min={0} value={draft.totalExperienceMonths} onChange={value => patch({ totalExperienceMonths: Number(value || 0) })} /></Form.Item><Form.Item label="Current location (ATS)"><Input value={draft.currentLocation} onChange={event => patch({ currentLocation: event.target.value })} /></Form.Item>
    <Form.Item label="Notice period"><Space.Compact block><InputNumber min={0} max={3650 / noticeFactor} step={noticeUnit === 'Months' ? 0.5 : 1} style={{ width: '100%' }} value={draft.noticePeriodDays > 0 ? Number((draft.noticePeriodDays / noticeFactor).toFixed(2)) : undefined} onChange={value => patch({ noticePeriodDays: Math.round(Number(value || 0) * noticeFactor) })} /><Select value={noticeUnit} style={{ width: 104 }} onChange={setNoticeUnit} options={[{ value: 'Days', label: 'Days' }, { value: 'Months', label: 'Months' }]} /></Space.Compact></Form.Item><Form.Item label="Highest qualification (ATS)"><Input value={draft.highestQualification} onChange={event => patch({ highestQualification: event.target.value })} /></Form.Item>
    <Form.Item label="Current annual CTC (LPA)"><InputNumber min={0} max={10000} step={0.1} addonAfter="LPA" value={lpa(draft.currentCtc)} onChange={value => patch({ currentCtc: Math.round(Number(value || 0) * 100000) })} /></Form.Item><Form.Item label="Expected annual CTC (LPA)"><InputNumber min={0} max={10000} step={0.1} addonAfter="LPA" value={lpa(draft.expectedCtc)} onChange={value => patch({ expectedCtc: Math.round(Number(value || 0) * 100000) })} /></Form.Item>
    <Form.Item label="Source"><Select value={draft.sourceType} onChange={sourceType => patch({ sourceType })} options={['Direct', 'Employee Referral', 'Consultant', 'Vendor', 'Job Portal', 'Campus'].map(value => ({ value, label: value }))} /></Form.Item><Form.Item label="Profile status"><Select value={draft.profileStatus} onChange={profileStatus => patch({ profileStatus })} options={['Active', 'Inactive', 'Joined', 'Archived'].map(value => ({ value, label: value }))} /></Form.Item>
    <Form.Item label="Consent"><Select value={draft.consentStatus} onChange={consentStatus => patch({ consentStatus })} options={['Pending', 'Granted', 'Revoked'].map(value => ({ value, label: value }))} /></Form.Item><Form.Item label="Retention until"><Input type="date" value={draft.retentionUntil?.slice(0, 10) || ''} onChange={event => patch({ retentionUntil: event.target.value || null })} /></Form.Item>
  </Form>{children}</>}</RecruitmentEditorDrawer>
}
