namespace Payroll.API.Models;
public class WorkflowMaster { public int Id { get; set; } public int? ClientId { get; set; } public string Code { get; set; } = ""; public string Name { get; set; } = ""; public string ResourceType { get; set; } = ""; public bool IsActive { get; set; } = true; public List<WorkflowStage> Stages { get; set; } = []; }
public class WorkflowStage { public int Id { get; set; } public int WorkflowId { get; set; } public int StageOrder { get; set; } public string Name { get; set; } = ""; public string ApproverType { get; set; } = ""; public int? ApproverUserId { get; set; } }
public class WorkflowInstance { public long Id { get; set; } public int WorkflowId { get; set; } public string ResourceType { get; set; } = ""; public string ResourceId { get; set; } = ""; public int RequestorUserId { get; set; } public string PayloadJson { get; set; } = "{}"; public string Status { get; set; } = ""; public DateTime CreatedAt { get; set; } }
public class WorkflowTask { public long Id { get; set; } public long InstanceId { get; set; } public int StageId { get; set; } public string StageName { get; set; } = ""; public string ResourceType { get; set; } = ""; public string ResourceId { get; set; } = ""; public string PayloadJson { get; set; } = "{}"; public int ApproverUserId { get; set; } public string ApproverName { get; set; } = ""; public string ActorName { get; set; } = ""; public string Status { get; set; } = ""; public string Comment { get; set; } = ""; public DateTime CreatedAt { get; set; } public DateTime? ActionedAt { get; set; } }
public class SaveWorkflowRequest { public int Id { get; set; } public int? ClientId { get; set; } public string Code { get; set; } = ""; public string Name { get; set; } = ""; public string ResourceType { get; set; } = ""; public bool IsActive { get; set; } = true; public List<WorkflowStage> Stages { get; set; } = []; }
public class StartWorkflowRequest { public int WorkflowId { get; set; } public string ResourceType { get; set; } = ""; public string ResourceId { get; set; } = ""; public string PayloadJson { get; set; } = "{}"; }
public class WorkflowActionRequest { public string Comment { get; set; } = ""; }
public class WorkflowApprover { public int Id { get; set; } public string DisplayName { get; set; } = ""; public string Email { get; set; } = ""; public int? ClientId { get; set; } public string ClientName { get; set; } = ""; }
public class WorkflowApproverPreview { public string ApproverType { get; set; } = ""; public string ResolutionStatus { get; set; } = "Unresolved"; public bool IsDynamic { get; set; } public WorkflowApprover? Approver { get; set; } public string Message { get; set; } = ""; }
public class WorkflowActivity { public long Id { get; set; } public string ActivityCode { get; set; } = ""; public string DisplayName { get; set; } = ""; public string ModuleCode { get; set; } = ""; public string ResourceType { get; set; } = ""; public string Description { get; set; } = ""; public bool IsActive { get; set; } = true; }
public class SaveWorkflowActivityRequest { public long Id { get; set; } public string ActivityCode { get; set; } = ""; public string DisplayName { get; set; } = ""; public string ModuleCode { get; set; } = ""; public string ResourceType { get; set; } = ""; public string Description { get; set; } = ""; public bool IsActive { get; set; } = true; }
public class WorkflowActionRule { public long Id { get; set; } public string ActivityCode { get; set; } = ""; public string HttpMethod { get; set; } = ""; public string PathPattern { get; set; } = ""; public string ResourceType { get; set; } = ""; public string ResourceIdSource { get; set; } = "route.id"; public string ResourceIdRouteKey { get; set; } = "id"; public string ClientIdSource { get; set; } = ""; public string ClientIdSql { get; set; } = ""; public string ClientLookupTable { get; set; } = ""; public string ClientLookupKeyColumn { get; set; } = ""; public string ClientLookupClientColumn { get; set; } = ""; public int? WorkflowId { get; set; } public string TriggerMode { get; set; } = "AfterSuccess"; public bool IsActive { get; set; } = true; }
public class SaveWorkflowActionRuleRequest { public long Id { get; set; } public string ActivityCode { get; set; } = ""; public string HttpMethod { get; set; } = ""; public string PathPattern { get; set; } = ""; public string ResourceType { get; set; } = ""; public string ResourceIdSource { get; set; } = "route.id"; public string ClientIdSource { get; set; } = ""; public string ClientIdSql { get; set; } = ""; public string ClientLookupTable { get; set; } = ""; public string ClientLookupKeyColumn { get; set; } = ""; public string ClientLookupClientColumn { get; set; } = ""; public int? WorkflowId { get; set; } public string TriggerMode { get; set; } = "AfterSuccess"; public bool IsActive { get; set; } = true; }
public class ResourceState { public long Id { get; set; } public string ResourceType { get; set; } = ""; public string ResourceId { get; set; } = ""; public string CurrentState { get; set; } = ""; public long? WorkflowInstanceId { get; set; } public int CreatedBy { get; set; } public DateTime CreatedOn { get; set; } public int ModifiedBy { get; set; } public DateTime ModifiedOn { get; set; } }
public class DepartmentHeadAssignment { public int Id { get; set; } public int ClientId { get; set; } public string Department { get; set; } = ""; public int UserId { get; set; } public string UserName { get; set; } = ""; }
public class SaveDepartmentHeadAssignmentRequest { public int ClientId { get; set; } public string Department { get; set; } = ""; public int UserId { get; set; } }
public class WorkflowHistoryItem { public long Id { get; set; } public string WorkflowName { get; set; } = ""; public string ResourceType { get; set; } = ""; public string ResourceId { get; set; } = ""; public string PayloadJson { get; set; } = "{}"; public string RequestorName { get; set; } = ""; public string Status { get; set; } = ""; public DateTime CreatedAt { get; set; } public DateTime? CompletedAt { get; set; } }
