namespace Payroll.API.Models;
public class WorkflowMaster { public int Id { get; set; } public int? ClientId { get; set; } public string Code { get; set; } = ""; public string Name { get; set; } = ""; public string ResourceType { get; set; } = ""; public bool IsActive { get; set; } = true; public List<WorkflowStage> Stages { get; set; } = []; }
public class WorkflowStage { public int Id { get; set; } public int WorkflowId { get; set; } public int StageOrder { get; set; } public string Name { get; set; } = ""; public string ApproverType { get; set; } = ""; public int? ApproverUserId { get; set; } }
public class WorkflowInstance { public long Id { get; set; } public int WorkflowId { get; set; } public string ResourceType { get; set; } = ""; public string ResourceId { get; set; } = ""; public int RequestorUserId { get; set; } public string PayloadJson { get; set; } = "{}"; public string Status { get; set; } = ""; public DateTime CreatedAt { get; set; } }
public class WorkflowTask { public long Id { get; set; } public long InstanceId { get; set; } public int StageId { get; set; } public string StageName { get; set; } = ""; public string ResourceType { get; set; } = ""; public string ResourceId { get; set; } = ""; public string PayloadJson { get; set; } = "{}"; public int ApproverUserId { get; set; } public string Status { get; set; } = ""; public DateTime CreatedAt { get; set; } }
public class SaveWorkflowRequest { public int Id { get; set; } public int? ClientId { get; set; } public string Code { get; set; } = ""; public string Name { get; set; } = ""; public string ResourceType { get; set; } = ""; public bool IsActive { get; set; } = true; public List<WorkflowStage> Stages { get; set; } = []; }
public class StartWorkflowRequest { public int WorkflowId { get; set; } public string ResourceType { get; set; } = ""; public string ResourceId { get; set; } = ""; public string PayloadJson { get; set; } = "{}"; }
public class WorkflowActionRequest { public string Comment { get; set; } = ""; }
public class WorkflowApprover { public int Id { get; set; } public string DisplayName { get; set; } = ""; public string Email { get; set; } = ""; public int? ClientId { get; set; } public string ClientName { get; set; } = ""; }
public class DepartmentHeadAssignment { public int Id { get; set; } public int ClientId { get; set; } public string Department { get; set; } = ""; public int UserId { get; set; } public string UserName { get; set; } = ""; }
public class SaveDepartmentHeadAssignmentRequest { public int ClientId { get; set; } public string Department { get; set; } = ""; public int UserId { get; set; } }
public class WorkflowHistoryItem { public long Id { get; set; } public string WorkflowName { get; set; } = ""; public string ResourceType { get; set; } = ""; public string ResourceId { get; set; } = ""; public string PayloadJson { get; set; } = "{}"; public string RequestorName { get; set; } = ""; public string Status { get; set; } = ""; public DateTime CreatedAt { get; set; } public DateTime? CompletedAt { get; set; } }
